### ISSUE TITLE
How to add a category to get them in the dropdown while creating the event in calendar

### ISSUE THREAD

**Issue by mack2deauna** [microsoft/vsts-team-calendar#322] opened 2020-10-06 12:55 UTC
How to add a category to get them in the dropdown while creating the event in calendar

**Comment by coke** [comment] 2021-05-03 20:06
Duplicate of #313

**Comment by MOlausson** [comment] 2023-06-19 10:13
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.

**Closed by MOlausson** 2023-06-19 10:13 UTC
