### ISSUE TITLE
Ability to change Event Colours

### ISSUE THREAD

**Issue by SeasiderTom** [Microsoft/vsts-team-calendar#155] opened 2017-05-31 14:25 UTC
Hi 

Would like the ability to be able to change event colours. at the moment colours are asigned automatically and events can have similar colour you can't change it.

Thanks
Thomas

**Comment by nschonni** [comment] 2017-05-31 21:05
Dupe of #154

**Comment by willsmythe** [comment] 2017-06-09 13:33
Duplicate.

**Closed** 2017-06-09 13:33 UTC
