### ISSUE TITLE
Get the calendar data through a REST request.

### ISSUE THREAD

**Issue by ghost** [microsoft/vsts-team-calendar#175] opened 2017-09-22 12:28 UTC
Hi,
I'm looking for a way of getting the calendar data through a REST request?

I have found this article but only shows how to get settings data and not documents data.
https://docs.microsoft.com/en-us/vsts/extend/develop/data-storage#rest-apis

Thanks,
Rui

**Comment by Korayem** [comment] 2018-04-22 09:09
Duplicate of #133

**Comment by MOlausson** [comment] 2023-06-19 08:24
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.

**Closed by MOlausson** 2023-06-19 08:24 UTC
