### ISSUE TITLE
Days Off - Not working for Individuals added to their team as part of a group alias

### ISSUE THREAD

**Issue by sksileski** [microsoft/vsts-team-calendar#250] opened 2019-09-10 19:25 UTC
Our developers are all added to Teams in our project as part of a group alias 
My account was added individually, as were a few others.
Only those people who were added individually can use "Add Days Off" as individuals.
For all others when selecting "Add Days Off", the dialog prompts them to schedule for their entire group - as individuals the OK button remains grayed out. 
ie. we can't use this feature for our entire Development org in Capacity Planning - and we need it badly.
Is there any plan to address this functionality in the future?
The current configuration doesn't adversely affect us in ANY other Azure Devops extensions or core functionality in our environment.

**Comment by sksileski** [comment] 2019-09-10 19:36
Please note, that we also tested to see if the user had to be a Team Administrator to add Days Off
I attempted (as an Administrator) to Add Days Off for individual members of our groups. The OK button was grayed out each time, but I could Add Days Off for people added individually who were not administrators.

**Comment by SCordesHum** [comment] 2019-09-24 16:32
We are experiencing the same issue.  This is a significant hindrance to being able to manage team members (Roles) in just one place (Active Directory groups).  As is, with each addition or departure from the team, we have to update the AD group _and_ put them in the ADO dev team.

**Comment by ruturaj-h** [comment] 2020-01-13 19:56
Hi, work Rest client doesn't support users added a group alias. So even if I show users the actual call to create the day off would fail.

**Comment by ruturaj-h** [comment] 2020-01-17 15:36
Duplicate of #158

**Comment by MOlausson** [comment] 2023-06-19 09:47
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.

**Closed by MOlausson** 2023-06-19 09:47 UTC
