### ISSUE TITLE
Share Calendar to Outlook

### ISSUE THREAD

**Issue by pmmcmullen94** [microsoft/vsts-team-calendar#221] opened 2018-06-10 20:36 UTC
I saw a couple of open issues that were requesting sharing the calendar to outlook but they were from a few years ago so I didn't want to continue with a stale request.

Is there any way to do this? Even if it's hacky but works. I would like to integrate this in VSTS and TFS to see all of my upcoming items next to my existing outlook items. Thanks!

**Comment by froboy** [comment] 2020-08-13 14:17
Duplicate of #64. Unless an issue is closed there's no reason to duplicate.

**Comment by MOlausson** [comment] 2023-06-19 09:24
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.

**Closed by MOlausson** 2023-06-19 09:24 UTC
