### ISSUE TITLE
AAD groups not being parsed when added to the Team

### ISSUE THREAD

**Issue by bthomas46** [microsoft/vsts-team-calendar#287] opened 2020-01-03 21:09 UTC
When I add an AAD group to a team I cannot see those users when I want to add a day off entry for a user. I can only assign to users that have been assigned directly to the team.

**Comment by ruturaj-h** [comment] 2020-01-13 19:56
Hi, work Rest client doesn't support users added a group alias. So even if I show users the actual call to create the day off would fail.

**Comment by ruturaj-h** [comment] 2020-01-16 15:49
Duplicate of #250

**Comment by ruturaj-h** [comment] 2020-01-17 15:37
Duplicate of #158

**Closed** 2023-06-19 09:44 UTC
