### ISSUE TITLE
Outlook integration or export as ics

### ISSUE THREAD

**Issue by M-WOLF** [microsoft/vsts-team-calendar#99] opened 2016-10-03 22:16 UTC
Outlook integration or export as ics would be great

**Comment by Stoffe** [comment] 2017-01-17 15:42
An integration with the Outlook calendar would be super needed, I want a common calendar that can hold all information about the project, and sync with our sharepoint site as well.
Integration with Outlook is a necessary feature!

**Comment by ggondim** [comment] 2017-05-29 23:09
Not just export but also publish the iCal for integration with another agendas (Google Calendar, etc.)

**Comment by nicksterx** [comment] 2018-02-01 19:27
Duplicate of #64

**Comment by MOlausson** [comment] 2023-06-19 07:36
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.

**Closed by MOlausson** 2023-06-19 07:36 UTC
Labels: enhancement
