### ISSUE TITLE
Unable to add event and the day off details

### ISSUE THREAD

**Issue by Vivek-CB** [microsoft/vsts-team-calendar#182] opened 2017-11-01 07:26 UTC
Dear Team,

I am unable to add event and the day off details under 'Calendar' of my VSTS account.
Once clicked on  'Add Event' or "Add Days off', the same pop up window ( window with option for adding days off / add event) is getting displayed at the left side bottom of the VSTS page. If we are clicking on this window, nothing is happening. Please help.
Attached the screenshot for your reference.
![issue](https://user-images.githubusercontent.com/33241544/32264297-100a9dbe-bf04-11e7-88ec-12a13e61f3fb.jpg)

**Comment by smpilo** [comment] 2017-11-02 17:27
duplicate of [this one](https://github.com/Microsoft/vsts-team-calendar/issues/180)

**Comment by smpilo** [comment] 2017-11-02 17:29
FYI it's working now, you should consider closing this...

**Comment by Olivija1** [comment] 2017-11-03 08:33
Hi, 
This is **still not** working for On Site deployment TFS 2017 Update .
Could you kindly take a look. 

Thank you in advance!

/Olivija

**Comment by veerapanenirakesh** [comment] 2017-11-03 14:52
Unable edit an event

**Comment by chouincorp** [comment] 2017-11-03 15:24
:8080/tfs/_public/_Bundling/Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:35 Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Object.gt [as getTypeName] (:8080/tfs/_public/_Bundling/Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:35)
    at n.getHttpClient (:8080/tfs/_public/_Bundling/Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:59)
    at CalendarView._getTeamMembers (:8080/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/team-calendar/0.5.11/assetbyname/dist/Calendar/Views.js:463)
    at CalendarView._addEvent (:8080/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/team-calendar/0.5.11/assetbyname/dist/Calendar/Views.js:434)
    at i.executeAction (:8080/tfs/_static/tfs/Dev15.M117.5/_scripts/TFS/min/VSS/Controls/Menus.js:3)
    at i.execute (:8080/tfs/_static/tfs/Dev15.M117.5/_scripts/TFS/min/VSS/Controls/Menus.js:3)
    at i._onClick (:8080/tfs/_static/tfs/Dev15.M117.5/_scripts/TFS/min/VSS/Controls/Menus.js:3)
    at HTMLLIElement.<anonymous> (:8080/tfs/_public/_Bundling/Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:44)
    at HTMLLIElement.dispatch (jquery.min.js:3)
    at HTMLLIElement.r.handle (jquery.min.js:3)

**Comment by david-cosmo** [comment] 2017-11-03 16:34
Also not working for TFS 2017 update 2 on-premise deployment.  Same issue described in original post... pop-up window just displays in lower left hand corner of window.

**Comment by ootjersb** [comment] 2017-11-17 13:10
same problem here using TFS2017 Update 2

**Closed** 2023-06-19 08:29 UTC
