### ISSUE TITLE
Unable to create events if my region is United kingdom

### ISSUE THREAD

**Issue by galiana** [Microsoft/vsts-team-calendar#27] opened 2016-03-15 09:16 UTC
Hi,
I have been trying to create several events with the same result.
When I click on add, the default format is MM/dd/yyyy. When I leave the date fields, it shows a validation error because the dates are not valid, then I select them with the date picker, and it changes to dd/MM/yyyy. Click OK, and I get no error, but nothing appears on the calendar.
I changed my profile in visualstudio.com, to be on region = United states, back to the calendar, and it works smoothly with the date format as MM/dd/yyy

**Comment by sebwulf** [comment] 2016-03-30 09:26
I am having the same issue. After changing my profile language to "English (United States)" I can create events and do not get a validation error for the date values.
We have an international team in our VSO project. Having everybody work with their familiar locale would be very helpful.

**Comment by sebwulf** [comment] 2016-03-30 14:10
Some more info:
I am normaly working with the german locale, using "dd.MM.yyyy" as a format for the dates.
After some debugging in the browser and digging around in the source, I think the issue is that the start and end dates are stored in the format of the locales user and later the parsing of the stored values fails and stores "Invalid date" in the date fields. 
There seems to be a mismatch between the format for storing the dates (uses the current users profile locale) and the loading of the dates in calendar.js:259. The loading code expects timezone information in the date string, which is not present.

**Comment by sebwulf** [comment] 2016-04-12 08:22
I am still having issues after last udpate to the calendar (04/11/16). I cannot create events and days off any more. Clicking "Ok" in the edit dialog does not create an event.

Chromes JS debugger reports an invalid time format when using the german locale.
![invalidt ime format](https://cloud.githubusercontent.com/assets/18163736/14453981/41997214-0098-11e6-8b18-aa47110adac4.PNG)
This is in Dialog.js.

**Comment by hajohns** [comment] 2016-04-12 13:16
Thank you for pointing this out, it should be fixed now! Please let us know if you're still seeing problems.

**Comment by sebwulf** [comment] 2016-04-12 13:38
Events are working fine now. I can create and edit.

I am still having problems with days off. Creating an entry works fine, but editing the dates is not saved correctly. I can see the entry moving in the calendar after clicking "OK" but once I reload the page, the entry is back at its inital day.

**Comment by hajohns** [comment] 2016-04-12 15:03
I am unable to repro, but we just published a fix for similar issue I was seeing, which may have solved the problem. If the issue persists, please let me know if the problem is on Days Off made through the Calendar, through the Backlogs Capacity page, or both. Thank you!

**Comment by sebwulf** [comment] 2016-04-15 07:43
I am still able to reproduce the problem with editing days off. It does not matter which locale is set in my profile or if the day off was created in the backlog capacities page or the calendar. 

To reproduce it:
1. Create  a day off in the calendar or the capacities page (I tested with single days off, longer days off show the same behaviour)
2. Edit the day off in the calendar (change date to the next day)
3. Close the edit dialog, the day off moves to the new date
4. Reload the calendar page
--> The day off moves back to the original date.

In Chromes F12 dev tools I can see a PATCH request to the affected teammembers id and the JSON for the day off still has the old dates. Could there be an issue with writing the new dates to the JSON structure?

**Comment by sebwulf** [comment] 2016-04-15 19:25
The latest changes did it. Editing existing days off works properly now. 
Thanks everybody!

**Closed** 2016-04-15 19:29 UTC
Labels: bug
